### ISSUE TITLE
8bitdo pro2 Controller not working

### ISSUE THREAD

**Issue by PittStone** [LakoMoor/reGTA#1]
**Describe the bug**
The 8Bitdo Pro2 Controller can not be configured in Controller Options. 
the controller.db is in the folder but nothing happens ingame.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Version**
Tell us what version you're running. Find out using the debug menu (Ctrl-M, Debug -> Version Text)
If you send a screenshot just enable it beforehand.

**Comment by LakoMoor** [comment]
Is it recognized on the computer as an xbox controller?

**Comment by LakoMoor** [comment]
I have updated the file [gamecontrollerdb.txt](https://github.com/LakoMoor/reGTA/blob/re3/gamefiles/gamecontrollerdb.txt) . Try to replace it in your files.
